if not exist $(INTERMEDIATE_DIR)$(Configuration).FEATURES del $(ROOT_DIR)intermediate\$(SolutionName)\include\cairo-features.h
echo /* Generated by VS Project File  Do not edit. */ > $(ROOT_DIR)intermediate\$(SolutionName)\include\cairo-features.h
echo #ifndef CAIRO_FEATURES_H >> $(ROOT_DIR)intermediate\$(SolutionName)\include\cairo-features.h
echo #define CAIRO_FEATURES_H >> $(ROOT_DIR)intermediate\$(SolutionName)\include\cairo-features.h
type $(INTERMEDIATE_DIR)$(Configuration).FEATURES >> $(ROOT_DIR)intermediate\$(SolutionName)\include\cairo-features.h
echo #endif >> $(ROOT_DIR)intermediate\$(SolutionName)\include\cairo-features.h